[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
audiopus = "0.2.0"
base64 = "0.23.1"
bytes = "1.12.1"
cpal = "0.18.1"
futures-util = "0.3.34"
ring = "0.17.14"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tokio-tungstenite = { version = "0.30.0", features = ["native-tls"] }
webrtc = "0.17.1"
zeroize = { version = "1.8.1", features = ["derive"] }
argon2 = "0.5"
chacha20poly1305 = "0.10"
rand = "0.8"
rfd = "0.14"
iced = { version = "0.14.0", features = ["tokio", "image", "canvas"] }
nnnoiseless = { version = "0.5.2", default-features = false }
dirs = "7.0.0"
region = "3.0"
secrecy = "0.8"
chrono = "0.4.45"
