[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
audiopus = "0.2.0"
bytes = "1.12.1"
cpal = "0.18.1"
futures-util = "0.3.34"
iced = { version = "0.12.1", features = ["tokio"] }
ring = "0.17.14"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tokio-tungstenite = "0.30.0"
webrtc = "0.17.1"
zeroize = "1.9.0"
